# Generated by Django 5.0.4 on 2024-04-30 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Test", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
            },
        ),
    ]
