# Generated by Django 5.0.4 on 2024-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_auto_20191124_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=500),
        ),
    ]
